#table configuration example
# storage data. currently only fillfactor is allowed

#set the fillfactor for all the tables 
[storage]
fillfactor = 100 

#sets the fillfactor for all the tables in the schema foo
[storage.foo]
fillfactor = 80 

#set the fillfactor for the table foo.bar
[storage.foo.bar]
fillfactor = 30 

